[2024-03-28T00:00:05.165+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-28T00:00:05.170+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-28T00:00:05.170+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-03-28T00:00:05.170+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-03-28T00:00:05.170+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-03-28T00:00:05.176+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2024-03-27 00:00:00+00:00
[2024-03-28T00:00:05.179+0000] {standard_task_runner.py:55} INFO - Started process 48305 to run task
[2024-03-28T00:00:05.181+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmptt0rcw1_']
[2024-03-28T00:00:05.182+0000] {standard_task_runner.py:83} INFO - Job 65: Subtask store_user
[2024-03-28T00:00:05.211+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.store_user scheduled__2024-03-27T00:00:00+00:00 [running]> on host 2be32c994b3e
[2024-03-28T00:00:05.239+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2024-03-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-27T00:00:00+00:00
[2024-03-28T00:00:05.240+0000] {postgres.py:129} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2024-03-28T00:00:05.243+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-03-28T00:00:05.245+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-03-28T00:00:05.250+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20240327T000000, start_date=20240328T000005, end_date=20240328T000005
[2024-03-28T00:00:05.282+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-03-28T00:00:05.290+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
